version: '2.1'
orbs:
  matlab: mathworks/matlab@dev:v1-rc
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests
workflows:
  build:
    jobs:
      - build

