name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        release: [R2023a, R2023b]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.release }}
      - name: Run command
        uses: matlab-actions/run-command@v2-rc0
        with:
          startup-options: matlabVer = ver('matlab'); assert(~isempty(matlabVer));
