name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-rc0
        with:
          products: MATLAB
          cache: true
      - name: Start display server
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Run tests
        uses: matlab-actions/run-tests@v2-rc0
        with:
          statup-options: -webui -logfile "output.log"
